# Generated by Django 5.0.6 on 2024-05-20 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
