# Generated by Django 5.0.6 on 2024-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_tokens_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
